import { ethers } from "ethers";
import { getEVMProvider } from "./rpc";

// 1inch API Base URL (Standard for public use, though private keys are better for production)
const ONENETWORK_API_BASE = "https://api.1inch.dev/swap/v6.0";

// Chain IDs for 1inch
const CHAIN_IDS = {
    ethereum: 1,
    base: 8453
};

// Common token addresses (Mainnet)
export const EVM_TOKEN_MINTS: Record<string, string> = {
    ETH: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee", // Native ETH
    USDC: "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
    USDT: "0xdac17f958d2ee523a2206206994597c13d831ec7",
    BASE_ETH: "0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee",
    BASE_USDC: "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
};

export interface EVMQuote {
    toAmount: string;
    tx: {
        to: string;
        data: string;
        value: string;
        gas: number;
        gasPrice: string;
    };
    feeAmount: string;
}

/**
 * Gets a quote from 1inch and applies smart fee logic
 */
export async function getEVMQuote(
    fromSymbol: string,
    toSymbol: string,
    amount: number,
    chain: "ethereum" | "base",
    userAddress: string
): Promise<EVMQuote | null> {
    try {
        const chainId = CHAIN_IDS[chain];
        const fromToken = EVM_TOKEN_MINTS[fromSymbol] || fromSymbol;
        const toToken = EVM_TOKEN_MINTS[toSymbol] || toSymbol;
        
        const decimals = fromSymbol === "ETH" ? 18 : 6; // Basic assumption, should fetch from contract
        const amountInWei = ethers.parseUnits(amount.toString(), decimals);

        // Smart Fee Logic: 1%
        const feePercent = parseFloat(process.env.FEE_PERCENTAGE || "0.01");
        const feeBps = feePercent * 10000;
        
        // Construct 1inch Swap URL
        // Note: Real 1inch API requires an API Key in headers
        const query = new URLSearchParams({
            src: fromToken,
            dst: toToken,
            amount: amountInWei.toString(),
            from: userAddress,
            slippage: "1", // 1%
            disableEstimate: "true",
            fee: feeBps.toString() // 1inch automatically sends fee to your referrer address
        });

        // For this implementation, we simulate the 1inch response to allow testing without an API key
        // In Mainnet, replace with actual fetch to api.1inch.dev
        const mockToAmount = (amount * 2500 * (1 - feePercent)).toString(); // Mock price
        
        return {
            toAmount: ethers.parseUnits(mockToAmount, 6).toString(),
            feeAmount: (amount * feePercent).toString(),
            tx: {
                to: "0x1111111254fb6c44bac0bed2854e76f90643097d", // 1inch Router
                data: "0x", // Generated by 1inch API
                value: amountInWei.toString(),
                gas: 250000,
                gasPrice: "20000000000"
            }
        };
    } catch (error) {
        console.error("EVM Quote error:", error);
        return null;
    }
}

/**
 * Executes an EVM swap via 1inch
 */
export async function executeEVMSwap(
    wallet: ethers.Wallet,
    fromSymbol: string,
    toSymbol: string,
    amount: number,
    chain: "ethereum" | "base"
): Promise<string | null> {
    try {
        const quote = await getEVMQuote(fromSymbol, toSymbol, amount, chain, wallet.address);
        if (!quote) throw new Error("Could not get swap quote");

        const provider = await getEVMProvider(chain);
        const connectedWallet = wallet.connect(provider);

        // 1. ERC20 Approval (If not sending ETH)
        if (fromSymbol !== "ETH") {
            // Logic to approve 1inch router to spend your tokens
            console.log("Approving 1inch router...");
        }

        // 2. Send Swap Transaction
        const tx = await connectedWallet.sendTransaction({
            to: quote.tx.to,
            data: quote.tx.data,
            value: fromSymbol === "ETH" ? quote.tx.value : 0,
            gasLimit: 300000
        });

        console.log(`⏳ Swap sent on ${chain}:`, tx.hash);
        await tx.wait();
        
        return tx.hash;
    } catch (error) {
        console.error("EVM Swap execution error:", error);
        return null;
    }
}
